### ISSUE TITLE
Getting this error when jailing someone

### ISSUE THREAD

**Issue by ForthtuN** [TanguyOrtegat/esx_jb_realtimejailer#4]
Im getting this error when i try to jail someone, i don't know which line of code i should look at since it doesen't point me to any so i need help.

https://i.imgur.com/g4VeUgF.jpg
```
[esx_jb_jailer] Mettre en prison en JailPoliceStation2 :FortuN pour 60 secs - commande entree par PappsenTV 
[ERROR] [MySQL] [esx_jb_realtimejailer] An error happens on MySQL for query "[object Object]": ER_BAD_NULL_ERROR: Column 'identifier' cannot be null 
[91mError: (node:19860) UnhandledPromiseRejectionWarning: Error: ER_BAD_NULL_ERROR: Column 'identifier' cannot be null 
at Query.Sequence._packetToError (mysql-async.js:244:14) 
at Query.ErrorPacket (mysql-async.js:2109:18) 
at Protocol._parsePacket (mysql-async.js:5938:23) 
at Parser.write (mysql-async.js:6195:12) 
at Protocol.write (mysql-async.js:5698:16) 
at Socket.<anonymous> (mysql-async.js:693:28) 
at emitOne (events.js:116:13) 
at Socket.emit (events.js:211:7) 
at addChunk (_stream_readable.js:263:12) 
at readableAddChunk (_stream_readable.js:250:11) 
-------------------- 
at Pool.query (mysql-async.js:4728:23) 
at Promise (mysql-async.js:4967:14) 
at new Promise (<anonymous>) 
at execute (mysql-async.js:4965:26) 
at Object.global.exports [as callback] (mysql-async.js:4982:5) 
at citizen:/scripting/v8/main.js:87:41[0m 
[91mError: (node:19860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)[0m ```

**Comment by TanguyOrtegat** [comment]
i did fix unjail try now again

**Comment by TanguyOrtegat** [comment]
what did you do to have that error ?

**Comment by LoffeKoffe** [comment]
Downgrade mysql async or update the mysql parts of the script

**Comment by TanguyOrtegat** [comment]
or add column identifier maybe
